# Generated by Django 4.0.6 on 2022-07-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_desription_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
